name: shital_video_editor
description: "A new Flutter package project."
version: 0.0.1
homepage:

# environment:
#   sdk: ^3.10.3
#   flutter: ">=1.17.0"

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6                           # Used for state management and navigation
  ffmpeg_kit_flutter_new: ^4.1.0        # Used for video editing
  image_picker: ^1.2.0                  # Used for picking images and videos
  mime: ^2.0.0                          # Used for getting mime type of files
  video_thumbnail: ^0.5.6               # Used for getting thumbnails of the picked video
  video_player: ^2.9.5                  # Used for playing videos
  intl: ^0.20.2                       # Used for formatting date and time
  path_provider: ^2.1.2                 # Used for generating output file path
  http:                                 # Used for making HTTP requests - Packages dependency
  cupertino_icons: ^1.0.2               # Used for more icons
  path: ^1.9.1                          # Used for path operations
  uuid: ^4.2.2                          # Used for generating unique IDs for projects
  saver_gallery: ^4.1.0                 # Used for saving the exported videos to the gallery
  percent_indicator: ^4.2.3             # Used for showing progress of video export
  file_picker: ^10.3.7                  # Used for picking audio files.
  audioplayers: ^5.2.1                  # Used for playing audio files along with the video
  flex_color_picker: ^3.3.1             # Used for font and background text color picker
  shared_preferences: ^2.2.2            # Used for storing user preferences (theme, language, etc.)
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - fonts/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Century Gothic
      fonts:
        - asset: fonts/CenturyGothic-Regular.ttf
        - asset: fonts/CenturyGothic-Bold.ttf
          weight: 700
        - asset: fonts/CenturyGothic-Italic.ttf
          style: italic
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
